### ISSUE TITLE
Лабы оаип 

### ISSUE THREAD

**Issue by jeniagt** [Andrague/BA-P#1]
Привет! Можешь скинуть пожалуйста недостающие файлы 4 лабы!

**Comment by Andrague** [comment]
4-ая  лаба написана для С++Builder

ср, 28 дек. 2022 г., 11:06 jeniagt ***@***.***>:

**Comment by jeniagt** [comment]
Не могу выполнить файл в С++ Builder, может весь проект сохранился?
